# Generated by Django 4.2.30 on 2026-04-12 18:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('initiator', 'Инициатор (Производство)'), ('purchaser', 'Закупщик (Снабжение)'), ('analyst', 'Аналитик'), ('manager', 'Руководитель'), ('admin', 'Администратор')], default='initiator', max_length=20, verbose_name='Роль')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Подразделение')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код МТР')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. изм.')),
                ('gost', models.CharField(blank=True, max_length=200, verbose_name='ГОСТ/ТУ')),
                ('technical_specs', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('criticality', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=10, verbose_name='Критичность')),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Минимальный запас')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Материал / Оборудование',
                'verbose_name_plural': 'Материалы / Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена, руб.')),
                ('delivery_days', models.PositiveIntegerField(verbose_name='Срок поставки, дней')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='Условия оплаты')),
                ('logistics_notes', models.TextField(blank=True, verbose_name='Условия логистики')),
                ('quote_date', models.DateField(verbose_name='Дата предложения')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действительно до')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_quotes', to='core.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Ценовое предложение',
                'verbose_name_plural': 'Ценовые предложения',
                'ordering': ['-quote_date', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=30, unique=True, verbose_name='Номер заявки')),
                ('department', models.CharField(max_length=200, verbose_name='Подразделение')),
                ('need_date', models.DateField(verbose_name='Дата необходимости')),
                ('criticality', models.CharField(choices=[('planned', 'Плановая'), ('emergency', 'Аварийная')], default='planned', max_length=10, verbose_name='Тип заявки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На рассмотрении'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('ordered', 'Заказ размещён'), ('completed', 'Исполнена')], default='draft', max_length=20, verbose_name='Статус')),
                ('justification', models.TextField(blank=True, verbose_name='Обоснование потребности')),
                ('rejection_comment', models.TextField(blank=True, verbose_name='Комментарий при отклонении')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Утверждено')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_requests', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Рейтинг (1–10)')),
                ('delivery_reliability', models.DecimalField(decimal_places=1, default=95.0, max_digits=5, verbose_name='Надёжность поставок, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('qty_available_at_warehouse', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Доступно на складе')),
                ('qty_to_purchase', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='К закупке')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Целевая цена, руб.')),
                ('justification_for_choice', models.TextField(blank=True, verbose_name='Обоснование выбора поставщика')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaserequest', verbose_name='Заявка')),
                ('selected_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pricequote', verbose_name='Выбранное предложение')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата доставки')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен поставщику'), ('confirmed', 'Подтверждён'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Сумма, руб.')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.purchaserequest', verbose_name='Заявка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщикам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pricequote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_quotes', to='core.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Объект')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал операций',
                'verbose_name_plural': 'Журнал операций',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Место хранения')),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Кол-во на складе')),
                ('qty_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Зарезервировано')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='core.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Складской остаток',
                'verbose_name_plural': 'Складские остатки',
                'ordering': ['material__name', 'location'],
                'unique_together': {('material', 'location')},
            },
        ),
    ]
