# Generated by Django 4.2.30 on 2026-05-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('sources_total', models.PositiveIntegerField(default=0, verbose_name='Источников всего')),
                ('sources_success', models.PositiveIntegerField(default=0, verbose_name='Источников успешно')),
                ('sources_failed', models.PositiveIntegerField(default=0, verbose_name='Источников с ошибкой')),
                ('products_found', models.PositiveIntegerField(default=0, verbose_name='Товаров найдено')),
                ('quotes_created', models.PositiveIntegerField(default=0, verbose_name='Предложений создано')),
                ('quotes_updated', models.PositiveIntegerField(default=0, verbose_name='Предложений обновлено')),
                ('error_log', models.TextField(blank=True, verbose_name='Журнал ошибок')),
            ],
            options={
                'verbose_name': 'Запуск парсинга',
                'verbose_name_plural': 'Запуски парсинга',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('website', models.URLField(max_length=500, verbose_name='Сайт')),
                ('category_hint', models.CharField(blank=True, max_length=200, verbose_name='Подсказка категории')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Оценка уверенности')),
                ('reason', models.TextField(blank=True, verbose_name='Обоснование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверен')),
                ('detected_contacts', models.JSONField(blank=True, default=dict, verbose_name='Контакты')),
                ('detected_categories', models.JSONField(blank=True, default=list, verbose_name='Категории')),
                ('detected_catalog_urls', models.JSONField(blank=True, default=list, verbose_name='URL каталогов')),
                ('detected_product_urls', models.JSONField(blank=True, default=list, verbose_name='URL товаров')),
                ('has_prices', models.BooleanField(default=False, verbose_name='Есть цены')),
                ('has_contacts', models.BooleanField(default=False, verbose_name='Есть контакты')),
                ('has_requisites', models.BooleanField(default=False, verbose_name='Есть реквизиты/ИНН')),
                ('has_delivery_rf', models.BooleanField(default=False, verbose_name='Доставка по РФ')),
                ('has_product_cards', models.BooleanField(default=False, verbose_name='Есть карточки товаров')),
                ('site_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP статус сайта')),
                ('site_response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время ответа, мс')),
                ('supplier_score', models.FloatField(default=0.0, verbose_name='Рейтинг поставщика')),
                ('risk_flags', models.JSONField(blank=True, default=list, verbose_name='Риски')),
            ],
            options={
                'verbose_name': 'Кандидат поставщика',
                'verbose_name_plural': 'Кандидаты поставщиков',
                'ordering': ['-supplier_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDiscoveryQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Поисковый запрос')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос поиска поставщиков',
                'verbose_name_plural': 'Запросы поиска поставщиков',
                'ordering': ['query'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('queries_total', models.PositiveIntegerField(default=0, verbose_name='Запросов всего')),
                ('candidates_found', models.PositiveIntegerField(default=0, verbose_name='Кандидатов найдено')),
                ('candidates_created', models.PositiveIntegerField(default=0, verbose_name='Кандидатов создано')),
                ('candidates_updated', models.PositiveIntegerField(default=0, verbose_name='Кандидатов обновлено')),
                ('error_log', models.TextField(blank=True, verbose_name='Журнал ошибок')),
            ],
            options={
                'verbose_name': 'Запуск поиска поставщиков',
                'verbose_name_plural': 'Запуски поиска поставщиков',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название источника')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('source_type', models.CharField(choices=[('product', 'Карточка товара'), ('listing', 'Листинг категории'), ('search', 'Страница поиска')], default='listing', max_length=20, verbose_name='Тип источника')),
                ('category_hint', models.CharField(blank=True, max_length=200, verbose_name='Подсказка категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('parser_strategy', models.CharField(default='generic', max_length=50, verbose_name='Стратегия парсинга')),
                ('request_delay_seconds', models.PositiveIntegerField(default=3, verbose_name='Задержка, сек')),
                ('max_items_per_run', models.PositiveIntegerField(default=10, verbose_name='Макс. товаров за запуск')),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный парсинг')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_sources', to='core.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Источник парсинга',
                'verbose_name_plural': 'Источники парсинга',
                'ordering': ['-is_active', 'supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='ParsedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(max_length=500, verbose_name='Наименование на сайте')),
                ('normalized_name', models.CharField(blank=True, max_length=500, verbose_name='Нормализованное наименование')),
                ('external_code', models.CharField(blank=True, max_length=100, verbose_name='Артикул / код на сайте')),
                ('category_detected', models.CharField(blank=True, max_length=200, verbose_name='Категория (определена)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена, руб.')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name='Наличие')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки, дней')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Производитель')),
                ('product_url', models.URLField(blank=True, max_length=500, verbose_name='URL товара')),
                ('characteristics', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('match_score', models.FloatField(default=0.0, verbose_name='Оценка сопоставления')),
                ('ai_comment', models.TextField(blank=True, verbose_name='Комментарий ИИ-сопоставления')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_products', to='core.material', verbose_name='Материал (сопоставлен)')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_products', to='core.parsingsource', verbose_name='Источник')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_products', to='core.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Найденный товар',
                'verbose_name_plural': 'Найденные товары',
                'ordering': ['-parsed_at'],
            },
        ),
    ]
